services:
  db:
    image: mysql:8.0.27
    container_name: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - wp_network
    ports:
      - 9036:3306
  wordpress:
    image: wordpress:latest
    container_name: wp
    volumes:
      - wp_data:/var/www/html
    restart: always
    networks:
      - public
      - wp_network
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:
  wp_data:
networks:
  public:
    external: true
  wp_network:
    name: 'wp_network'