services:
  jenkins:
    container_name: jenkins
    build: .
    image: trannhan380381/jenkins_with_docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    networks:
      - public
networks:
  public:
    external: true